import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import BottomNavBar from "../components/BottomNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <BottomNavBar />
      </body>
    </html>
  );
}
